apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-orders-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scalable-orders-backend
  template:
    metadata:
      labels:
        app: scalable-orders-backend
    spec:
      containers:
        - name: backend
          image: scalable-orders-backend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              value: "postgres://davidduenas@host.minikube.internal:5432/scalable_orders"

---
apiVersion: v1
kind: Service
metadata:
  name: scalable-orders-backend
spec:
  type: NodePort
  selector:
    app: scalable-orders-backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080

