apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-backend
spec:
  replicas: 1        # Escenario 2: empezamos con 1 r√©plica
  selector:
    matchLabels:
      app: orders-backend
  template:
    metadata:
      labels:
        app: orders-backend
    spec:
      containers:
        - name: backend
          image: scalable-orders-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@db:5432/scalable_orders"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: orders-backend-svc
spec:
  type: NodePort
  selector:
    app: orders-backend
  ports:
    - port: 3000        # puerto dentro del cluster
      targetPort: 3000  # puerto del contenedor
      
